{{- if and .Values.deployment.kong.enabled .Values.autoscaling.kong.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "supabase.kong.fullname" . }}
  minReplicas: {{ .Values.autoscaling.kong.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.kong.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.kong.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.kong.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.kong.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.kong.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
