{{- if and .Values.deployment.vector.enabled .Values.autoscaling.vector.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "supabase.vector.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "supabase.vector.fullname" . }}
  minReplicas: {{ .Values.autoscaling.vector.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.vector.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.vector.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.vector.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.vector.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.vector.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
