{{- if and .Values.deployment.realtime.enabled .Values.autoscaling.realtime.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "supabase.realtime.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "supabase.realtime.fullname" . }}
  minReplicas: {{ .Values.autoscaling.realtime.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.realtime.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.realtime.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.realtime.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.realtime.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.realtime.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
