-- AUTOGENERATED for supabase-kubernetes-cnpg chart
-- pg_stat_statements extension must be created in the postgres database
-- See: https://www.postgresql.org/docs/current/pgstatstatements.html
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;